### ISSUE TITLE
Update Inheritance Documentation

### ISSUE THREAD

**Issue by Brandon-Shea** [LearnOnDemandSystems/docs#1000]
In my opinion, we shouldn't be saying "etc" in technical documentation.  We should list out which pieces of the Lab Profile are inherited and what are not, specifically.  For example, are LCA's inherited or can they differ?

**Link to the document**: 
https://docs.skillable.com/lod/inherit-lab-profile.md

**Screenshots (optional)**: 

![image](https://github.com/LearnOnDemandSystems/docs/assets/140736198/eca912d2-9755-466c-819b-bad3b45b50a1)

**Comment by dillonreese** [comment]
@Brandon-Shea Do you have a list of the items that are inherited?

**Comment by Brandon-Shea** [comment]
I don't have an exact list of the items because it's not in the documentation.  I asked Product though, so I can post back here if I get a response from them.
