### ISSUE TITLE
MB-310 LAB

### ISSUE THREAD

**Issue by mbaradadev** [LearnOnDemandSystems/docs#1011]
**Description of proposed changes**: 
Instructions in LAB must be in FRENCH when I have a french profile in Microsoft Learn

**Link to the document**: 
Enter link here

**Screenshots (optional)**:

**Comment by dillonreese** [comment]
This repository is used to store and manage documentation.
Please contact our [Customer Support team](http://www.skillable.com/customer-support/) for assistance.
