### ISSUE TITLE
Unable to complete required lab

### ISSUE THREAD

**Issue by itsshalini** [LearnOnDemandSystems/docs#1013]
**Description of proposed changes**: 
Unable to complete required lab
[Implement secure cloud solutions](https://gsi.learnondemand.net/Lab/47101?instructionSetLang=en&classId=556885) (Expected Duration 1 hours, 30 minutes)
AZ-204T00-A Developing Solutions for Microsoft Azure [Cloud Slice Provided], Learning Path 07 (CSS)

LAB user doesn't have required permission to view Keyvault secrets

**Link to the document**: 
Enter link here

**Screenshots (optional)**:

**Comment by dillonreese** [comment]
This repository is used to store and manage documentation.
Please contact our [Customer Support team](http://www.skillable.com/customer-support/) for assistance.
