### ISSUE TITLE
Incorrect documentation of setActivityResult in Python

### ISSUE THREAD

**Issue by r-b-g-b** [LearnOnDemandSystems/docs#1036]
**Description of proposed changes**: 

The [docs](https://docs.skillable.com/lod/activities.md#python) say you can set a scored result using:

```python
setActivityResult(0.5);
```

but that results in the message "Script did not return a boolean or scored result."

Instead you have to pass the score as a keyword argument to work.

```python
setActivityResult(score=0.5)
```

**Link to the document**: 
https://docs.skillable.com/lod/activities.md#python

**Screenshots (optional)**:

**Comment by dillonreese** [comment]
Thanks @r-b-g-b. This document has been updated.
