### ISSUE TITLE
Not able to reconnect the system for skillable lab

### ISSUE THREAD

**Issue by AparnaShyam** [LearnOnDemandSystems/docs#1038]
Connection is lost and not able to reconnect the system while doing the lab "[Network Security Groups and Application Security Groups](https://msle.learnondemand.net/Lab/62684?instructionSetLang=en&classId=578450) (Expected Duration 1 hours, 30 minutes)
AZ-500T00-A Microsoft Azure Security Technologies [Cloud Slice Provided], Lab 05 (CSS)"

Due to this issue , I was not able to clear the resources as well 
Kindly check and revert

**Comment by AparnaShyam** [comment]
<img width="956" alt="image" src="https://github.com/LearnOnDemandSystems/docs/assets/19794965/33438f57-6870-4077-8ad7-7895f16240a5">

**Comment by AparnaShyam** [comment]
Kindly allow me to perform the lab from the interrupted step

**Comment by dillonreese** [comment]
This repository is used to store and manage documentation.
Please contact our [Customer Support team](http://www.skillable.com/customer-support/) for assistance.
