### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by akweli** [LearnOnDemandSystems/docs#1039]
I am seeking guidance or support to make edits to my account, but I'm currently unsure about the specific steps or procedures required for this task. I would greatly appreciate it if someone could reach out to me at 301-768-6339 to provide detailed instructions or assistance regarding the account editing process. Your help in this matter would be immensely valuable. Thank you for your attention to this request.

**Comment by akweli** [comment]
none

**Comment by paulieguk** [comment]
This Github repo is for reporting issues with the Skillable documentation.  Please reach out to Skillable customer support and raise a ticket for help with your account - https://www.skillable.com/customer-support
