### ISSUE TITLE
Access denied 

### ISSUE THREAD

**Issue by samsonmobisa** [LearnOnDemandSystems/docs#1049]
How can one signup to the lab. I tried to login but my access was denied
my ID is 37197846
Host	SEA-HV33
Datacenter	US West (Seattle)

**Comment by paulieguk** [comment]
Hi,

You have placed an issue against our documentation.  This is not used for customer support.  Please contact our 24*7 customer support services at https://skillable.com/customer-support
[http://www.skillable.com/wp-content/uploads/2021/10/FullImage_3_2x-1024x400.png]<https://skillable.com/customer-support>
Customer Support<https://skillable.com/customer-support>
Get help with Skillable courses, labs, and account access.
skillable.com


Thank you,
Paul


Paul Gregory

Solution Architect

+44 (0) 7970 155 456  (TZ | UTC 0:00)

***@***.***

skillable.com<https://skillable.com/> | LinkedIn<https://www.linkedin.com/company/skillable/> | X<https://twitter.com/skillable>

[A green tick and a black background  Description automatically generated]<https://skillable.com/>





________________________________
From: Samson Mobisa ***@***.***>
Sent: 23 January 2024 2:35 PM
To: LearnOnDemandSystems/docs ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LearnOnDemandSystems/docs] Access denied (Issue #1049)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe. Also, please think before you reply-all to external recipients.

How can one signup to the lab. I tried to login but my access was denied
my ID is 37197846
Host SEA-HV33
Datacenter US West (Seattle)

**Comment by samsonmobisa** [comment]
okay
