### ISSUE TITLE
"An API example that contains these parameters is displayed on the Lab Profile. To view the example, navigate to the Manage Instructions Sets page on the Lab Profile. Next, select the Columns menu in the upper-right, and enable the API example column. An API example will be displayed next to each instruction set, with the ID and language parameters."

### ISSUE THREAD

**Issue by hsdemolabs** [LearnOnDemandSystems/docs#1052]
**Description of proposed changes**: 
Instructions Sets doc page contains invalid/outdated instructions?

**Link to the document**: 
Cannot link directly due to loaded in frame.

**Screenshots (optional)**: 

It appears that the documentation page for Instructions sets may have an out of date reference:

Text: An API example that contains these parameters is displayed on the Lab Profile. To view the example, navigate to the Manage Instructions Sets page on the Lab Profile. Next, select the Columns menu in the upper-right, and enable the API example column. An API example will be displayed next to each instruction set, with the ID and language parameters.

I can't find where in the lab profile where you view this API. The only reference to them on the lab profile I can even find regarding instruction sets is on the advanced tab, it allows you to change the instructions source. Did the location of this API change? I'm trying to find examples of how you change the instruction set via an API lab launch.

**Comment by dillonreese** [comment]
@hsdemolabs To view this setting on a lab profile, you have to select "Edit instructions". From there, you can get to the Manage Instructions Sets menu by selecting the instruction set at the top of the window. 

If you have any additional questions or need additional assistance, please reach out to our [Customer Support Team](https://customersupport.skillable.com/Content/CustomerSupportRequestIntro).
