### ISSUE TITLE
Cloud Slice Guide - AWS page contains outdated AWS UI instructions

### ISSUE THREAD

**Issue by hsdemolabs** [LearnOnDemandSystems/docs#1053]
**Description of proposed changes**: 
This page should be updated to reflect the current AWS UI

**Link to the document**: 
Cannot link due to page being loaded in a frame

**Screenshots (optional)**: 

During the setup of AWS cloudslice I noticed that some of these instructions are out of date.

The most notable example is step 7: Next, select programmatic Access. This enables an access key ID and secret access key for the AWS API, CLI, SDK, and other development tools.

The setting referenced does not seem to exist anymore, I searched but was unable to find it. That said, I was able to complete the setup. The easiest thing to do may be to go through this setup today and check the entire instruction set for accuracy.

**Comment by dillonreese** [comment]
We have gone through this document and updated it according to the latest steps in AWS.
