### ISSUE TITLE
Page is missing referenced/linked sections

### ISSUE THREAD

**Issue by hsdemolabs** [LearnOnDemandSystems/docs#1054]
**Description of proposed changes**: 
The page lists/links to the following sections, but they are not present:
[Login Page Options tab settings](https://docs.skillable.com/tms/tms-administrators/tms-fundamentals/site-management.md#login-page-options-tab-settings)
[Top Navigation Menu tab](https://docs.skillable.com/tms/tms-administrators/tms-fundamentals/site-management.md#top-navigation-menu-tab)
[Contact HTML tab](https://docs.skillable.com/tms/tms-administrators/tms-fundamentals/site-management.md#contact-html-tab)
[Footer HTML tab](https://docs.skillable.com/tms/tms-administrators/tms-fundamentals/site-management.md#footer-html-tab)

**Link to the document**: 
https://docs.skillable.com/tms/tms-administrators/tms-fundamentals/site-management.md

**Comment by dillonreese** [comment]
We have updated this page to remove the erroneous links. Thank you for bringing this to our attention.
