### ISSUE TITLE
lauching the explore relational data in azure

### ISSUE THREAD

**Issue by Subasi-panta** [LearnOnDemandSystems/docs#1059]
**Description of proposed changes**: 
Enter description here

**Link to the document**: 
Enter link here

**Screenshots (optional)**:

**Comment by Subasi-panta** [comment]
please open the launch of explore relational azure in data

**Comment by paulieguk** [comment]
Hi,
This GitHub is now closed the Skillable documentation now has feedback options at the bottom of each page.  If your feedback is not related to the Skillable documentation please visit https://skillable.com/customer-support and contact our customer support team.

Thank you for your support and feedback.
Skillable.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
