### ISSUE TITLE
Add vscode extension

### ISSUE THREAD

**Issue by BernieWhite** [LearnOnDemandSystems/docs#215]
Just a suggestion, have you considered publishing an extension for Visual Studio Code to assist with markdown authoring?

I was thinking something similar to [DocFX](https://marketplace.visualstudio.com/items?itemName=ms-docfx.DocFX)

**Comment by dillonreese** [comment]
Thanks for the suggestion @BernieWhite!

This has been forwarded to our dev team for consideration, and may be available in the future. Unfortunately we do not have an ETA yet.
