### ISSUE TITLE
Lab completion

### ISSUE THREAD

**Issue by shubhamsinha14** [LearnOnDemandSystems/docs#393]
I have the worst experience with all of you. I continuously tried to be in touch with the customer support regarding my lab completion status. But despite helping me they are ignoring the problem.  I would never suggest anyone to use your lab on demand facility

**Comment by dillonreese** [comment]
@shubhamsinha14 Please submit a support ticket via [Customer Support](https://www.learnondemandsystems.com/customer-support/). Upon submitting a support ticket, you will receive an email in reference to your support ticket at the email address you used to submit the ticket. As a caution, please check your junk/spam folder if you do not receive an email reference to your ticket within an hour after submitting the ticket.
