### ISSUE TITLE
How do I get to my labs

### ISSUE THREAD

**Issue by lilbird662000** [LearnOnDemandSystems/docs#434]

**Comment by lilbird662000** [comment]
I've been taking the quizes and downloading the assignments. There are no directions. I really want to complete them, but can't since I can't find the assignments or labs

**Comment by dillonreese** [comment]
@lilbird662000 Please reach out to our Support team for assistance with this issue. You can contact them [here](https://www.learnondemandsystems.com/customer-support/).
