### ISSUE TITLE
500 - Internal Server Error

### ISSUE THREAD

**Issue by dabbkumar** [LearnOnDemandSystems/docs#442]
Hello Support, 

I'm getting the error "Status: 500 Internal Server Error" when I run a function inside Azure (last task of the last exercise).  I verified the code and it looks good.

Please help!

**Comment by dabbkumar** [comment]
Lab ID: AZ-203T04A(Implement Azure Security)

**Comment by dillonreese** [comment]
@dabbkumar Please contact our Support team for assistance with that error. You can contact them [here](https://lod.one/help).
