### ISSUE TITLE
Lab VM Screen Resolution Auto-Adjust

### ISSUE THREAD

**Issue by JeffSmalley** [LearnOnDemandSystems/docs#447]
When I am using Microsoft Windows VMs they keep adjusting to 800X600 display resolution. I need higher resolutions most of the time. I switch them to a higher resolution in the VM but they switch back to 800X600 when I adjust the environment like going full screen and back or adjust the width of the instruction pane. Very annoying.  How can I stop the VMs in your LOD portal from changing back to 800X600?????    I am a MCT and this wastes a lot of my teaching time having to switch it so many times..

Regards,
Jeff Smalley MCT
Chicagoville

**Comment by ZekeStarr** [comment]
Hi Jeff,

Please open a support ticket at [www.learnondemandsystems.com/support](www.learnondemandsystems.com/support), outlining this issue. We'll be happy to assist.

Regards,
Zeke Starr
