### ISSUE TITLE
CEH lab questions

### ISSUE THREAD

**Issue by kalirami** [LearnOnDemandSystems/docs#448]
The program is a good teaching software on how to use the tools but the fill in the questions seem to be written by a 9-year-old who doesn't know what to ask. I constantly spend 10 mins or more trying to figure out the exact question you are asking and how exactly you want it typed since its so case sensitive. Please either remove the fill in the questions or have someone else write the questions better and easier to understand.

Here is an example of the issue:
What is the command is used to Filter the HTTP traffic?

**Comment by dillonreese** [comment]
@kalirami Please reach out to our Support staff for assistance. They can be reached here: [LODS Support](https://lod.one/help).
