### ISSUE TITLE
typo in documentation lod-api-result

### ISSUE THREAD

**Issue by Bergiu** [LearnOnDemandSystems/docs#500]
https://github.com/LearnOnDemandSystems/docs/blob/master/lod/lod-api/lod-api-result.md#examquestion

The field `Type` can contain 4 strings. One of them is `TextExacthWord` and i'm not sure if this is a typo but maybe it should be `TextExactWord`?

**Comment by dillonreese** [comment]
This should have been `TextExactWord`. This has been updated in the documentation. Thanks!

**Comment by Bergiu** [comment]
Thanks for your fast reply
