### ISSUE TITLE
Instructor in lod-api-class is not required on errors

### ISSUE THREAD

**Issue by Bergiu** [LearnOnDemandSystems/docs#501]
as the documentation says the instructor is required, but if i get an error response this key is not given.

examples 1:
`client.class_(ClassParameters(id=8))`
results in:
`{'Error': 'Class not found', 'Status': 0}`

example 2:
`client.class_()`
results in:
`{'Error': 'id is a required parameter', 'Status': 0}`

**Comment by ChadSpears** [comment]
Hello Bergiu

This was a case of Nullable vs. Required. 

An instructor is not required on the class, but if one is provided, the Instructor Id, FirstName and LastName will be provided.

Thanks again.
