### ISSUE TITLE
status and error keys are missing in most response documentations

### ISSUE THREAD

**Issue by Bergiu** [LearnOnDemandSystems/docs#502]
most (or all?) of the responses return the keys Status and Error, but they are missing in most of the documented Responses.

**Comment by Bergiu** [comment]
in some error cases the api doesn't even return the expected object but only {Status: ..., Error: ...}

**Comment by ChadSpears** [comment]
Hello Bergiu,

I went through and added the error messaging to the calls. All but one (GetLabInstructionsPackage) will return an error if it occurs. I'm not sure about the status, I will need to check those individually. Status will be either 1 (Success) or 0 (Failed) if it is supplied.
