### ISSUE TITLE
required fields are not correct

### ISSUE THREAD

**Issue by Bergiu** [LearnOnDemandSystems/docs#503]
in some of the api methods the required fields are wrong.

one example:
https://github.com/LearnOnDemandSystems/docs/blob/master/lod/lod-api/lod-api-catalog.md#deliveryregion

in this one the description is required, but in my api result i get a null value:
`{"LabSeries":[],"LabProfiles":[],"DeliveryRegions":[{"Id":2,"Name":"Australia","Description":"Servicing Australia, New Zealand, and south APAC"},{"Id":3,"Name":"Europe","Description":"European Datacenter Region"},{"Id":4,"Name":"Infrastructure-Only","Description":"Used to store objects for infrastructure. SHOULD NOT BE ASSIGNED PRODUCTION RESOURCES."},{"Id":1,"Name":"North America","Description":null},{"Id":5,"Name":"US West - Veritas","Description":null}],"Error":null,"Status":1}`
in the last two delivery regions the description is null: `{"Id":5,"Name":"US West - Veritas","Description":null}`

maybe the required and not-requireds are switched, because id an name are always given.

**Comment by Bergiu** [comment]
i'm not sure, but maybe you just need to rename the category (or categories) from required to nullable

**Comment by ChadSpears** [comment]
Thank you Bergiu,

Switching the category is what this needed.
