### ISSUE TITLE
confusing category names: required and nullable

### ISSUE THREAD

**Issue by Bergiu** [LearnOnDemandSystems/docs#504]
sometimes you use `required` as category name and sometime `nullable`, what do you mean with `required` and why do you mix it?

**Comment by ChadSpears** [comment]
Hello Bergiu, 

Thank you for pointing this out. 

Required is applied to to the parameters required to make an API call. If a parameter is required, you must specify it in your API call.
Nullable is applied to the response. If the value is nullable, we may not supply a value in the response

I have revised the API documentation to better reflect the differences, sorry for the confusion.
