### ISSUE TITLE
IDLx Lab Interface Overview

### ISSUE THREAD

**Issue by DamonFout** [LearnOnDemandSystems/docs#651]
**Description of proposed changes**: 
1. Chat with Lab Support on line 20
2. Work in that diff disks/lab changes are also done through Save/Exit menu

Line 20
- **Help**: The Help tab allows users to change the theme of the Lab Client, or change the Machine Remote Controller (if the lab has managed VMs). It also provides users with the ID of their lab instance along with other relevant details (depending on the type of lab launched), and links to view a FAQ, submit a support request, or report a bug.

- **Help**: The Help tab allows users to change the theme of the Lab Client, or change the Machine Remote Controller (if the lab has managed VMs). It also provides users with the ID of their lab instance along with other relevant details (depending on the type of lab launched), and links to view a FAQ, submit a support request, chat with lab support or report a bug.

Line 26
- **Save/Exit menu**: This menu is represented by three horizontal lines, in the upper-right corner of the Lab Console. This menu allows the lab to be saved (if saving is enabled on the lab by the lab author), or end the lab. This menu also allows lab authors to edit the lab instructions.

- **Save/Exit menu**: This menu is represented by three horizontal lines, in the upper-right corner of the Lab Console. This menu allows the lab to be saved (if saving is enabled on the lab by the lab author), or end the lab. This menu also allows lab authors to edit the lab instructions and save changes to the virtual environment.

**Link to the document**: 
https://github.com/LearnOnDemandSystems/docs/blame/master/lod/idlx-lab-interface-overview.md

**Comment by dillonreese** [comment]
This document was updated with these suggestions via [this pull request](https://github.com/LearnOnDemandSystems/docs/pull/654).
