### ISSUE TITLE
Lab Series

### ISSUE THREAD

**Issue by DamonFout** [LearnOnDemandSystems/docs#653]
**Description of proposed changes**: 
    Add line 33 for **Automatically Disable**

          1. **Automatically Disable**: The date that the lab series can be set to be disabled. A disabled series is not accessible to published the LMS and the labs within cannot be launched.

    Remove Duplicate line under **Publish**

**Link to the document**: 
https://github.com/LearnOnDemandSystems/docs/blob/master/lod/lab-series.md

**Comment by dillonreese** [comment]
This document was updated with these suggestions via [this pull request](https://github.com/LearnOnDemandSystems/docs/pull/654).
