### ISSUE TITLE
Allow Supplemental Recording Access

### ISSUE THREAD

**Issue by LodsCory** [LearnOnDemandSystems/docs#692]
**Description of proposed changes**: 
No info on Allow Supplemental Recording Access

**Link to the document**: 
https://docs.learnondemandsystems.com/tms/tms-administrators/courses-and-activities/overall/course-profile-explanation.md#prerequisites

**Screenshots (optional)**: 
 
![image](https://user-images.githubusercontent.com/62734074/128915031-abc80b67-1fbb-4038-821d-99f9a3be891e.png)

**Comment by dillonreese** [comment]
[This document](https://docs.learnondemandsystems.com/tms/tms-administrators/courses-and-activities/overall/course-profile-explanation.md) has been updated with an explanation for _Allow supplemental recording access_. 

Thanks @LodsCory!
