### ISSUE TITLE
Access courseware button is not visible for me

### ISSUE THREAD

**Issue by anshu0795** [LearnOnDemandSystems/docs#703]
i logged for class enrollment but here i am not able tp Access Courseware button.

so could you please tell me how i can access skillpipe.

**Comment by paulieguk** [comment]
The courseware button only becomes valid for MOC courses when the class starts assuming this feature is enabled for the organisation delivering the course.  The button just opens skillpipe.com and can auto sign you in.  LOD does not actually provide the courseware or the courseware key
https://docs.learnondemandsystems.com/tms/end-user-student-faqs/class-self-paced/access-my-courseware.md

**Comment by anshu0795** [comment]
In that case how I can access my course in skillpipe,Because in each
session instructor always says like you can access study material on
skillpipe.

FYI:- I am not Authorize  to skillpipe so I created a new account but it is
not showing any courses.

Regards

Anshul

**Comment by paulieguk** [comment]
Skillpipe is an external service provided by Microsoft and Avarto.  If you need to access your courseware outside of an LOD class you go to skillpipe.com.  If you have issues with your account or with courses you will need to speak with Avarto support.  It is a completely different company and they would not allow us to help you as we are not the account owner.  Avarto support can be contacted here: https://shop.courseware-marketplace.com/en-US/Content/Contact

**Comment by anshu0795** [comment]
Ok thank you for the information
