### ISSUE TITLE
Could not change keyboard layout (inaccurate help screenshots)

### ISSUE THREAD

**Issue by mohowzeh** [LearnOnDemandSystems/docs#731]
**Description of proposed changes**: 
In the lab VM, my goal was to change the keyboard layout to **Belgian (French)** whilst keeping the display and system language set to **English**. 

When trying to change the keyboard layout on the VM, the screenshots show on the help document do not match the screens presented in the VM itself. 

As a non-Windows specialist, I tried for 30 minutes and made several restarts. Eventually I managed it for Windows apps like Notepad (see screenshot), but not for Power BI. 
In Power BI, when I pressed 'a' on my keyboard, the VM stubbornly kept writing 'q'. (my keyboard being AZERTY). 

Please expand the documentation in the help section (see link below)
1. providing accurate screenshots
2. providing explanation how to make Power BI "listen" to the Windows settings. 

**Link to the document**: 
[https://docs.learnondemandsystems.com/lod/lab-interface-faqs/how-do-i-make-my-international-keyboard-work-in-the-lab-interface.md](url) 

**Screenshots (optional)**:
![2021-11-11_21-36-29_different control panel](https://user-images.githubusercontent.com/40325127/141365769-a812e8f5-e9ef-4e83-955c-9159e7b3c1cb.png)
 
![2021-11-11_21-41-10_language in control panel](https://user-images.githubusercontent.com/40325127/141367353-87068731-9e92-437d-976e-c05470b2a0b5.png)

![2021-11-11_21-55-07_correct letters in Notepad](https://user-images.githubusercontent.com/40325127/141368035-86abf3ed-48bd-4477-b3e6-55bc8b6a011f.png)

![2021-11-11_21-51-18_typing a keeps showing q in Power BI](https://user-images.githubusercontent.com/40325127/141367369-92ca9331-315d-47f2-b653-5035b149fc67.png)

**Comment by dillonreese** [comment]
Thanks @mohowzeh, can you explain which screenshots need to be updated, and what information they are missing? 

For a quicker resolution to the issue you're encountering, I would recommend reaching out to our [customer support team](https://skillable.com/customer-support/) and someone will be able to work with you to resolve it.

**Comment by mohowzeh** [comment]
Hi @dillonreese, sorry for the late reply, I was out due to illness. Thank you for the link to the customer support team, I will reach out to them. You can close this request.
