### ISSUE TITLE
Connection lost and can't find content as instructed

### ISSUE THREAD

**Issue by hungnguyen1110** [LearnOnDemandSystems/docs#758]
I'm doing lab 7 of Power BI (Designing a report in Power BI) and encouter 2 problems:
1, Connection lost, can't connect to the power BI through lab stimulator
2, Can't find the content as instructed 

![Erro2](https://user-images.githubusercontent.com/77108495/143943623-995ca9bc-3ae0-4bbc-a512-975d45b5cff7.png)
![Error](https://user-images.githubusercontent.com/77108495/143943625-b5f35f01-ada8-4f8f-873d-3c45c590519f.png)

**Comment by dillonreese** [comment]
Hello, 

Please reach out to our [customer support team](http://www.skillable.com/customer-support/) for assistance with this issue. 
This repository is used to store documentation, and isn't monitored by our support staff. 

Thanks!
