### ISSUE TITLE
Inconsistent documentation of Bash set_lab_variable.

### ISSUE THREAD

**Issue by WobblyMusicStand** [LearnOnDemandSystems/docs#770]
**Description of proposed changes**: 
Update to correct capitalization in all instances.

The BASH set_lab_variable is incorrectly given as "Set_Lab_Variable" in numerous instances on this document. Using it in an LCA will generate an error.

"Error executing script on 172.20.125.172 for FirstDisplayable lab life cycle action "Testing" line 5: Set_Lab_Variable: command not found"

**Link to the document**: 
[Enter link here](https://docs.learnondemandsystems.com/lod/variables.md)

**Screenshots (optional)**: 
![image](https://user-images.githubusercontent.com/20515066/146624689-2d959b3b-2335-4633-8830-425b9f20ab9a.png)
![image](https://user-images.githubusercontent.com/20515066/146624693-fdc73035-8363-4e64-acfd-9432dff705d0.png)

**Comment by dillonreese** [comment]
Thanks @WobblyMusicStand. This has been corrected in [this pull request](https://github.com/LearnOnDemandSystems/docs/pull/773).
