### ISSUE TITLE
/api/v3/labprofile returns key "Ram" not "RAM"

### ISSUE THREAD

**Issue by ServerAcademy** [LearnOnDemandSystems/docs#775]
**Description of proposed changes**: 
Response key "RAM" is incorrect. Server responds with "Ram"

**Link to the document**: 
https://docs.learnondemandsystems.com/lod/lod-api/lod-api-lab-profile.md

**Comment by dillonreese** [comment]
Thanks for the report. This has been corrected in the documentation.
