### ISSUE TITLE
I need the first lab

### ISSUE THREAD

**Issue by omahacheeks** [LearnOnDemandSystems/docs#806]
**Description of proposed changes**: 
Enter description here
I need my first lab. I finished it but I need to take screenshots of certain parts to complete my homework.
**Link to the document**: 
Enter link here

**Screenshots (optional)**:

**Comment by omahacheeks** [comment]
I finished my first lab without getting screenshots for my assignment. I need to redo my first lab.,=

**Comment by omahacheeks** [comment]
The second lab keeps coming up whenever I click Continue it starts my second lab

**Comment by dillonreese** [comment]
Hello, 

This repository is for housing and managing Skillable's documentation. If you are needing assistance with your lab, please contact our [customer support team](http://www.skillable.com/customer-support/).
