### ISSUE TITLE
Not able to create container

### ISSUE THREAD

**Issue by ramesh-undralla-by** [LearnOnDemandSystems/docs#819]
**Description of proposed changes**: 
am facing an issue for module : Module 2 - Developing AI Apps with Cognitive Services

**Link to the document**: 
Enter link here

<img width="958" alt="image" src="https://user-images.githubusercontent.com/75683959/167676017-2ab56eae-1a02-47f2-a9c8-daf4235f0823.png">

**Comment by dillonreese** [comment]
Hello @ramesh-undralla-by, this repository is used to store Skillable documentation. For assistance with your lab, please reach out to our [customer support team](http://www.skillable.com/customer-support/).
