### ISSUE TITLE
Email not sending

### ISSUE THREAD

**Issue by LeeAndrew23** [LearnOnDemandSystems/docs#857]
**Description of proposed changes**: 
Enter description here Comptia is not sending me emails to renew my password even after inputting it in

**Link to the document**: 
Enter link here

**Screenshots (optional)**:

**Comment by dillonreese** [comment]
Hello @LeeAndrew23, 

Apologies for the delay. This repository is used to store and manage documentation. 
Please contact our [Customer Support team](http://www.skillable.com/customer-support/) for assistance. 

Thanks
