### ISSUE TITLE
Best practice for VM password cannot be followed

### ISSUE THREAD

**Issue by grabinski** [LearnOnDemandSystems/docs#91]
In the section [**Recommendations and Best Practices**](https://github.com/LearnOnDemandSystems/docs/blob/master/lod/feature-focus/cloud-resource-templates/recommendations-and-best-practices.md#recommendations-and-best-practices) of the document **Use Azure ARM Template for Cloud Slice**, item number **6** in the list makes the recommendation to use the **@lab.CloudPortalCredential().Password** replacement token a VM password.

I wish this were possible; however, the generated password is only 10 characters long, and VMs require a 12 character password so this best practice guidance cannot be followed as written.

**Comment by coreyhynes** [comment]
Different resources have different password requirements.  If you want to randomize it but meet a minimum length, so something like **password@lab.CloudPortalCredential().Password** to add some length.  Another option is to combine @lab.labinstanceID with the Cloud Credential Password.  It's up to you.  Be creative.

**Comment by grabinski** [comment]
Thanks, Corey. I'll open a pull request to include this guidance in the documentation.
