### ISSUE TITLE
Common Style Guidelines are outdated and conflict with current Microsoft Style Guide

### ISSUE THREAD

**Issue by ephiax20** [LearnOnDemandSystems/docs#914]
Hi, 

**Description of proposed changes**: 
The 'Common Style Guidelines' section of the IDLx Authoring Guide references the Microsoft Manual of Style (MMS), 4th edition which, as far as I can tell, is over 11 years old now.  There are several contradictions with the current Microsoft Style guide which is available here: https://learn.microsoft.com/en-us/style-guide/

E.g. "If using the term check box, this is two words." from IDLx docs, which contradicts:
"Use checkbox, not box or check box"  from https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/c/check-checkbox-check-mark

Also, "Use click rather than choose or select" from IDLx docs, which contradicts this:
"Avoid this verb, which is specific to using a mouse. Instead, use verbs that work with multiple devices, such as select."  from https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/c/click

There may be other contradictions. 

**Link to the document**: 
https://docs.learnondemandsystems.com/guides/idl2/idlv2-authoring-guide-and-best-practice.md#common-style-guidelines:~:text=least%20__%20seconds.-,Common%20Style%20Guidelines,-This%20section%20includes

**Screenshots (optional)**:

**Comment by dillonreese** [comment]
@ephiax20, 
This document has been updated, thank you for the report!
