### ISSUE TITLE
Markdown alert not rendering

### ISSUE THREAD

**Issue by Jamoed** [LearnOnDemandSystems/docs#951]
**Description of proposed changes**: 
Edit markdown for help menu so that the alert renders according to markdown alert style. Browser used: Chrome

**Link to the document**: 
[Enter link here](https://docs.learnondemandsystems.com/tms/targets/class-enrollment-profile.md?appid=tms)

**Screenshots (optional)**: 
<img width="288" alt="image" src="https://user-images.githubusercontent.com/116977255/236841641-0338c78f-0400-499f-b168-3584b9232c97.png">

**Comment by dillonreese** [comment]
Thank you for the report. This has been corrected.
