### ISSUE TITLE
Issue with Lab 6

### ISSUE THREAD

**Issue by jalapr01** [LearnOnDemandSystems/docs#962]
**Description of proposed changes**: 
In lab 6, Exercise 2, task 2,  step #9, did not see the permissions page; but did see the Welcome page with the UPN
**Link to the document**: 
https://directions.learnondemand.net/Lab/47100?classId=536273

**Screenshots (optional)**: 
![image](https://github.com/LearnOnDemandSystems/docs/assets/98925405/a2049b93-2895-4404-90ce-10502a18e7b9)

**Comment by dillonreese** [comment]
This repository is used to store and manage documentation.
Please contact our [Customer Support team](http://www.skillable.com/customer-support/) for assistance.
