### ISSUE TITLE
Copy/paste into powershell does not work.

### ISSUE THREAD

**Issue by evanofjd** [LearnOnDemandSystems/docs#963]
AZ-204T00-A Developing Solutions for Microsoft Azure [No Azure Pass Required]
Lab 6: Implement user authentication and authorization

Task 5, step 2
Clicking the "T" does not cause the text to be pasted into powershell. It just results in ^V in the terminal.

**Comment by dillonreese** [comment]
This repository is used to store and manage documentation.
Please contact our [Customer Support team](http://www.skillable.com/customer-support/) for assistance.
